name: ci-pre-commit

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  pre-commit:
    uses: jay-withers/workflows/.github/workflows/pre-commit.yml@a4133d77f379bc1f3cd69870a75542facf306567 # v1.4.2
    with:
      terraform: true
